apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: demo-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:1.25.2
        ports:
        - containerPort: 80

